sources:
  include:
    - ../../../Sources

templates:
  - ../../Templates/Value Convertible/Int+ValueConvertibleTests.ejs

output:
  ../../../Tests/VoltTests/Data Objects/Value Convertible/Int+ValueConvertibleTests.swift
