sources:
  include:
    - ../../../Sources

templates:
  - ../../Templates/Value Convertible/Int+ConvertibleFromVoltValueTests.ejs

output:
  ../../../Tests/VoltTests/Data Objects/Value Convertible/Int+ConvertibleFromVoltValueTests.swift
