sources:
  include:
    - ../../Sources

  exclude:
    - ../../Sources/Volt/Public/Data Objects/Value/ValueConvertible/Int+ValueConvertible.swift

templates:
  - ../Templates/Int+ValueConvertible.ejs

output:
  ../../Sources/Volt/Public/Data Objects/Value/ValueConvertible/Int+ValueConvertible.swift
